[build]
  command = "yarn build"
  publish = ".output/public"

[build.environment]
  NODE_VERSION = "18.18.0"

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/server"
  status = 200
  force = true

[[redirects]]
  from = "/*"
  to = "/.netlify/functions/server"
  status = 200
